//! First-party SOL Terminal core.
//!
//! The terminal owns terminal semantics (PTY lifecycle, VT state, scrollback,
//! selection and keyboard input) but deliberately does not own a concrete
//! renderer, display connection, or clipboard protocol. Platform adapters plug
//! into the small traits below; deterministic fixtures exercise the same core
//! in CI without claiming a GPU, Wayland, or system clipboard was available.

use std::{
    collections::VecDeque,
    error::Error,
    fmt,
    io::{self, Write},
};

use portable_pty::{CommandBuilder, MasterPty, PtySize, native_pty_system};
use sol_app::{App, AppId};
use sol_design::color::Color;
use sol_graphics::Surface;
use sol_ui::{
    AccessibilityNode, Button, CommandPalette, CommandPaletteOutcome, InteractionTree, Key,
    KeyboardOutcome, PaletteCommand, SemanticControl,
};

const TERMINAL_COMMANDS: [PaletteCommand; 5] = [
    PaletteCommand {
        id: "terminal.new_tab",
        title: "Open a new terminal tab",
    },
    PaletteCommand {
        id: "terminal.close_tab",
        title: "Close active terminal tab",
    },
    PaletteCommand {
        id: "terminal.copy",
        title: "Copy terminal selection",
    },
    PaletteCommand {
        id: "terminal.paste",
        title: "Paste into terminal",
    },
    PaletteCommand {
        id: "terminal.search",
        title: "Search terminal scrollback",
    },
];

/// A terminal-core failure. The error deliberately does not expose an OS shell
/// command line so callers cannot accidentally treat executable text as shell
/// syntax.
#[derive(Debug)]
pub enum TerminalError {
    /// The requested terminal grid dimensions are unusable.
    InvalidDimensions,
    /// An adapter could not complete its operation.
    Adapter(String),
    /// A requested tab does not exist.
    UnknownTab(usize),
    /// There is no active tab.
    NoActiveTab,
}

impl fmt::Display for TerminalError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidDimensions => formatter.write_str("terminal dimensions must be non-zero"),
            Self::Adapter(message) => write!(formatter, "terminal adapter error: {message}"),
            Self::UnknownTab(tab) => write!(formatter, "terminal tab {tab} does not exist"),
            Self::NoActiveTab => formatter.write_str("terminal has no active tab"),
        }
    }
}

impl Error for TerminalError {}

impl From<io::Error> for TerminalError {
    fn from(error: io::Error) -> Self {
        Self::Adapter(error.to_string())
    }
}

/// A directly executed program and arguments. It is never interpolated into a
/// `sh -c` command, which keeps a configurable shell from becoming a second,
/// accidental shell-language parser in the Terminal app.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShellProgram {
    program: String,
    args: Vec<String>,
}

impl ShellProgram {
    /// Construct an explicit executable and argument vector.
    pub fn new(program: impl Into<String>, args: impl IntoIterator<Item = String>) -> Self {
        Self {
            program: program.into(),
            args: args.into_iter().collect(),
        }
    }

    /// Select the user's login shell, falling back to POSIX `sh` only when the
    /// environment has no shell preference. The value is passed as an executable
    /// path/name, not evaluated as source text.
    #[must_use]
    pub fn from_environment() -> Self {
        let program = std::env::var("SHELL").unwrap_or_else(|_| "/bin/sh".into());
        Self::new(program, Vec::new())
    }

    /// The executable passed directly to the PTY implementation.
    #[must_use]
    pub fn program(&self) -> &str {
        &self.program
    }

    /// The direct argument vector passed to the PTY implementation.
    #[must_use]
    pub fn args(&self) -> &[String] {
        &self.args
    }
}

/// Dimensions negotiated between the terminal grid and its PTY.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TerminalSize {
    /// Text columns.
    pub columns: u16,
    /// Text rows.
    pub rows: u16,
}

impl TerminalSize {
    /// Validate a grid size.
    pub fn new(columns: u16, rows: u16) -> Result<Self, TerminalError> {
        if columns == 0 || rows == 0 {
            return Err(TerminalError::InvalidDimensions);
        }
        Ok(Self { columns, rows })
    }
}

/// Runtime boundary for one spawned pseudoterminal.
pub trait PtySession: Send {
    /// Write bytes generated by keyboard input or paste into the PTY.
    fn write_input(&mut self, bytes: &[u8]) -> Result<(), TerminalError>;
    /// Inform the child process that the terminal grid changed size.
    fn resize(&mut self, size: TerminalSize) -> Result<(), TerminalError>;
    /// Report a child exit without blocking a frame.
    fn poll_exit(&mut self) -> Result<Option<i32>, TerminalError>;
    /// End the child during tab/application shutdown.
    fn terminate(&mut self) -> Result<(), TerminalError>;
}

/// Factory boundary, allowing process-free fixtures in deterministic tests.
pub trait PtyFactory {
    /// Spawn a direct executable in a newly allocated PTY.
    type Session: PtySession;
    fn spawn(
        &self,
        shell: &ShellProgram,
        size: TerminalSize,
    ) -> Result<Self::Session, TerminalError>;
}

/// Native Unix/Windows PTY adapter supplied by `portable-pty`.
#[derive(Debug, Default, Clone, Copy)]
pub struct NativePtyFactory;

/// A real child process and its PTY master. Reading output is intentionally
/// driven by a platform event-loop adapter in a native window integration; the
/// pure core consumes bytes through [`TerminalGrid::feed`].
pub struct NativePtySession {
    master: Box<dyn MasterPty + Send>,
    child: Box<dyn portable_pty::Child + Send + Sync>,
    writer: Box<dyn Write + Send>,
}

impl PtyFactory for NativePtyFactory {
    type Session = NativePtySession;

    fn spawn(
        &self,
        shell: &ShellProgram,
        size: TerminalSize,
    ) -> Result<Self::Session, TerminalError> {
        let system = native_pty_system();
        let pair = system
            .openpty(PtySize {
                rows: size.rows,
                cols: size.columns,
                pixel_width: 0,
                pixel_height: 0,
            })
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        let mut command = CommandBuilder::new(shell.program());
        for argument in shell.args() {
            command.arg(argument);
        }
        let child = pair
            .slave
            .spawn_command(command)
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        let writer = pair
            .master
            .take_writer()
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        Ok(NativePtySession {
            master: pair.master,
            child,
            writer,
        })
    }
}

impl PtySession for NativePtySession {
    fn write_input(&mut self, bytes: &[u8]) -> Result<(), TerminalError> {
        self.writer.write_all(bytes)?;
        self.writer.flush()?;
        Ok(())
    }

    fn resize(&mut self, size: TerminalSize) -> Result<(), TerminalError> {
        self.master
            .resize(PtySize {
                rows: size.rows,
                cols: size.columns,
                pixel_width: 0,
                pixel_height: 0,
            })
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        Ok(())
    }

    fn poll_exit(&mut self) -> Result<Option<i32>, TerminalError> {
        Ok(self
            .child
            .try_wait()
            .map_err(|error| TerminalError::Adapter(error.to_string()))?
            .map(|status| status.exit_code() as i32))
    }

    fn terminate(&mut self) -> Result<(), TerminalError> {
        self.child
            .kill()
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        Ok(())
    }
}

/// RGB true-color value received through an ANSI SGR sequence.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Rgb {
    /// Red channel.
    pub red: u8,
    /// Green channel.
    pub green: u8,
    /// Blue channel.
    pub blue: u8,
}

/// Terminal palette role, including xterm indexed and true-color values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TerminalColor {
    /// The active SOL terminal theme's foreground/background role.
    #[default]
    Default,
    /// An xterm palette entry.
    Indexed(u8),
    /// A 24-bit ANSI true-color value.
    Rgb(Rgb),
}

/// Styling retained by one terminal cell.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CellStyle {
    /// Foreground colour.
    pub foreground: TerminalColor,
    /// Background colour.
    pub background: TerminalColor,
    /// Bold ANSI SGR attribute.
    pub bold: bool,
}

impl Default for CellStyle {
    fn default() -> Self {
        Self {
            foreground: TerminalColor::Default,
            background: TerminalColor::Default,
            bold: false,
        }
    }
}

/// One renderer-neutral grid cell. `text` stores a Unicode scalar or a blank;
/// grapheme shaping remains the native text adapter's responsibility.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Cell {
    /// The character presented in this cell.
    pub text: String,
    /// ANSI style active when this cell was written.
    pub style: CellStyle,
}

impl Cell {
    fn blank(style: CellStyle) -> Self {
        Self {
            text: " ".into(),
            style,
        }
    }
}

/// Position in the currently visible grid.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct GridPosition {
    /// Zero-based row.
    pub row: u16,
    /// Zero-based column.
    pub column: u16,
}

/// A selected inclusive grid range.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Selection {
    /// Drag origin.
    pub anchor: GridPosition,
    /// Drag endpoint.
    pub focus: GridPosition,
}

/// One match found by the terminal's deterministic scrollback search.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SearchMatch {
    /// Row in the scrollback + visible-grid stream.
    pub row: usize,
    /// Unicode scalar offset in that row's plain text.
    pub column: usize,
}

/// Parser and retained terminal screen. It supports the VT/ANSI subset used by
/// typical shell prompts and colourized CLI tools: line movement, erase, cursor
/// addressing, indexed colours, and 24-bit SGR colours.
#[derive(Debug, Clone)]
pub struct TerminalGrid {
    size: TerminalSize,
    cells: Vec<Cell>,
    cursor: GridPosition,
    style: CellStyle,
    scrollback: VecDeque<Vec<Cell>>,
    scrollback_limit: usize,
}

impl TerminalGrid {
    /// Create a blank grid with bounded scrollback.
    pub fn new(size: TerminalSize, scrollback_limit: usize) -> Self {
        let style = CellStyle::default();
        Self {
            size,
            cells: vec![Cell::blank(style); usize::from(size.columns) * usize::from(size.rows)],
            cursor: GridPosition { row: 0, column: 0 },
            style,
            scrollback: VecDeque::new(),
            scrollback_limit,
        }
    }

    /// Return the grid dimensions.
    #[must_use]
    pub fn size(&self) -> TerminalSize {
        self.size
    }

    /// Return the active cursor location.
    #[must_use]
    pub fn cursor(&self) -> GridPosition {
        self.cursor
    }

    /// Return a visible cell.
    #[must_use]
    pub fn cell(&self, position: GridPosition) -> Option<&Cell> {
        self.index(position).map(|index| &self.cells[index])
    }

    /// Feed UTF-8 PTY output into the retained VT grid.
    pub fn feed(&mut self, text: &str) {
        let characters: Vec<char> = text.chars().collect();
        let mut index = 0;
        while index < characters.len() {
            if characters[index] == '\u{1b}' && characters.get(index + 1) == Some(&'[') {
                let start = index + 2;
                let mut end = start;
                while end < characters.len() && !characters[end].is_ascii_alphabetic() {
                    end += 1;
                }
                if let Some(final_byte) = characters.get(end).copied() {
                    let parameters: String = characters[start..end].iter().collect();
                    self.apply_csi(&parameters, final_byte);
                    index = end + 1;
                    continue;
                }
            }

            match characters[index] {
                '\n' => self.line_feed(),
                '\r' => self.cursor.column = 0,
                '\u{8}' => self.cursor.column = self.cursor.column.saturating_sub(1),
                '\u{7}' => {} // terminal bell belongs to an optional sound adapter
                character if !character.is_control() => self.put_character(character),
                _ => {}
            }
            index += 1;
        }
    }

    /// Resize without losing the newest visible text. A real PTY must be
    /// resized separately through [`PtySession::resize`].
    pub fn resize(&mut self, size: TerminalSize) {
        let old_rows: Vec<Vec<Cell>> = (0..self.size.rows).map(|row| self.row(row)).collect();
        self.size = size;
        self.cells =
            vec![Cell::blank(self.style); usize::from(size.columns) * usize::from(size.rows)];
        for (row_index, row) in old_rows
            .into_iter()
            .rev()
            .take(usize::from(size.rows))
            .rev()
            .enumerate()
        {
            for (column, cell) in row.into_iter().take(usize::from(size.columns)).enumerate() {
                let position = GridPosition {
                    row: row_index as u16,
                    column: column as u16,
                };
                let slot = self
                    .index(position)
                    .expect("resized grid position is in bounds");
                self.cells[slot] = cell;
            }
        }
        self.cursor.row = self.cursor.row.min(size.rows - 1);
        self.cursor.column = self.cursor.column.min(size.columns - 1);
    }

    /// Search retained scrollback and visible rows using a case-sensitive plain
    /// text query. Empty queries intentionally have no matches.
    #[must_use]
    pub fn search(&self, query: &str) -> Vec<SearchMatch> {
        if query.is_empty() {
            return Vec::new();
        }
        self.all_rows()
            .iter()
            .enumerate()
            .flat_map(|(row, cells)| {
                let line = row_text(cells);
                line.match_indices(query)
                    .map(|(column, _)| SearchMatch { row, column })
                    .collect::<Vec<_>>()
            })
            .collect()
    }

    /// Return selected visible text suitable for a clipboard adapter.
    #[must_use]
    pub fn selected_text(&self, selection: Selection) -> String {
        let (start, end) = if selection.anchor <= selection.focus {
            (selection.anchor, selection.focus)
        } else {
            (selection.focus, selection.anchor)
        };
        let mut lines = Vec::new();
        for row in start.row..=end.row.min(self.size.rows - 1) {
            let first = if row == start.row { start.column } else { 0 };
            let last = if row == end.row {
                end.column
            } else {
                self.size.columns - 1
            };
            let text: String = (first..=last)
                .filter_map(|column| self.cell(GridPosition { row, column }))
                .map(|cell| cell.text.as_str())
                .collect();
            lines.push(text);
        }
        lines.join("\n")
    }

    fn apply_csi(&mut self, parameters: &str, final_byte: char) {
        let values: Vec<u16> = if parameters.is_empty() {
            Vec::new()
        } else {
            parameters
                .split(';')
                .map(|part| part.parse().unwrap_or(0))
                .collect()
        };
        match final_byte {
            'm' => self.apply_sgr(&values),
            'H' | 'f' => {
                self.cursor.row = values
                    .first()
                    .copied()
                    .unwrap_or(1)
                    .saturating_sub(1)
                    .min(self.size.rows - 1);
                self.cursor.column = values
                    .get(1)
                    .copied()
                    .unwrap_or(1)
                    .saturating_sub(1)
                    .min(self.size.columns - 1);
            }
            'J' => {
                if values.first().copied().unwrap_or(0) == 2 {
                    self.cells.fill(Cell::blank(self.style));
                    self.cursor = GridPosition { row: 0, column: 0 };
                }
            }
            'K' => {
                let row = self.cursor.row;
                for column in self.cursor.column..self.size.columns {
                    self.set_cell(GridPosition { row, column }, Cell::blank(self.style));
                }
            }
            _ => {}
        }
    }

    fn apply_sgr(&mut self, values: &[u16]) {
        let values = if values.is_empty() { &[0] } else { values };
        let mut index = 0;
        while index < values.len() {
            match values[index] {
                0 => self.style = CellStyle::default(),
                1 => self.style.bold = true,
                22 => self.style.bold = false,
                30..=37 => {
                    self.style.foreground = TerminalColor::Indexed((values[index] - 30) as u8)
                }
                39 => self.style.foreground = TerminalColor::Default,
                40..=47 => {
                    self.style.background = TerminalColor::Indexed((values[index] - 40) as u8)
                }
                49 => self.style.background = TerminalColor::Default,
                90..=97 => {
                    self.style.foreground = TerminalColor::Indexed((values[index] - 90 + 8) as u8)
                }
                100..=107 => {
                    self.style.background = TerminalColor::Indexed((values[index] - 100 + 8) as u8)
                }
                38 | 48 if values.get(index + 1) == Some(&2) && index + 4 < values.len() => {
                    let color = TerminalColor::Rgb(Rgb {
                        red: values[index + 2] as u8,
                        green: values[index + 3] as u8,
                        blue: values[index + 4] as u8,
                    });
                    if values[index] == 38 {
                        self.style.foreground = color;
                    } else {
                        self.style.background = color;
                    }
                    index += 4;
                }
                38 | 48 if values.get(index + 1) == Some(&5) && index + 2 < values.len() => {
                    let color = TerminalColor::Indexed(values[index + 2] as u8);
                    if values[index] == 38 {
                        self.style.foreground = color;
                    } else {
                        self.style.background = color;
                    }
                    index += 2;
                }
                _ => {}
            }
            index += 1;
        }
    }

    fn put_character(&mut self, character: char) {
        let width = unicode_cell_width(character);
        if width == 0 {
            return;
        }
        if self.cursor.column + width > self.size.columns {
            self.line_feed();
            self.cursor.column = 0;
        }
        self.set_cell(
            self.cursor,
            Cell {
                text: character.to_string(),
                style: self.style,
            },
        );
        if width == 2 && self.cursor.column + 1 < self.size.columns {
            self.set_cell(
                GridPosition {
                    row: self.cursor.row,
                    column: self.cursor.column + 1,
                },
                Cell::blank(self.style),
            );
        }
        self.cursor.column += width;
        if self.cursor.column >= self.size.columns {
            self.line_feed();
            self.cursor.column = 0;
        }
    }

    fn line_feed(&mut self) {
        if self.cursor.row + 1 < self.size.rows {
            self.cursor.row += 1;
            return;
        }
        let first_row = self.row(0);
        if self.scrollback_limit > 0 {
            self.scrollback.push_back(first_row);
            while self.scrollback.len() > self.scrollback_limit {
                self.scrollback.pop_front();
            }
        }
        let columns = usize::from(self.size.columns);
        self.cells.rotate_left(columns);
        let final_start = self.cells.len() - columns;
        self.cells[final_start..].fill(Cell::blank(self.style));
    }

    fn row(&self, row: u16) -> Vec<Cell> {
        let start = usize::from(row) * usize::from(self.size.columns);
        self.cells[start..start + usize::from(self.size.columns)].to_vec()
    }

    fn all_rows(&self) -> Vec<Vec<Cell>> {
        self.scrollback
            .iter()
            .cloned()
            .chain((0..self.size.rows).map(|row| self.row(row)))
            .collect()
    }

    fn index(&self, position: GridPosition) -> Option<usize> {
        (position.row < self.size.rows && position.column < self.size.columns).then_some(
            usize::from(position.row) * usize::from(self.size.columns)
                + usize::from(position.column),
        )
    }

    fn set_cell(&mut self, position: GridPosition, cell: Cell) {
        if let Some(index) = self.index(position) {
            self.cells[index] = cell;
        }
    }
}

fn row_text(cells: &[Cell]) -> String {
    cells
        .iter()
        .map(|cell| cell.text.as_str())
        .collect::<String>()
        .trim_end()
        .to_owned()
}

fn unicode_cell_width(character: char) -> u16 {
    // A deliberately small, dependency-free East Asian wide-character table.
    // Combining marks consume no additional cell; advanced grapheme shaping is
    // delegated to the native text renderer.
    if matches!(character, '\u{0300}'..='\u{036f}') {
        0
    } else if matches!(character, '\u{1100}'..='\u{115f}' | '\u{2e80}'..='\u{a4cf}' | '\u{ac00}'..='\u{d7a3}' | '\u{f900}'..='\u{faff}' | '\u{fe10}'..='\u{fe19}' | '\u{ff01}'..='\u{ff60}')
    {
        2
    } else {
        1
    }
}

/// Clipboard contract. A native Wayland clipboard bridge can implement this;
/// CI uses [`MemoryClipboard`] and does not claim desktop clipboard coverage.
pub trait ClipboardAdapter {
    /// Store selected text.
    fn set_text(&mut self, text: String) -> Result<(), TerminalError>;
    /// Obtain text to paste into the active PTY.
    fn get_text(&self) -> Result<String, TerminalError>;
}

/// Deterministic clipboard fixture.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct MemoryClipboard {
    text: String,
}

impl ClipboardAdapter for MemoryClipboard {
    fn set_text(&mut self, text: String) -> Result<(), TerminalError> {
        self.text = text;
        Ok(())
    }
    fn get_text(&self) -> Result<String, TerminalError> {
        Ok(self.text.clone())
    }
}

/// Renderer-neutral terminal frame. A native SolUI renderer consumes cells and
/// token roles; Terminal never creates a Slint/GPU object directly.
#[derive(Debug, Clone, PartialEq)]
pub struct TerminalFrame {
    /// Physical surface size after fractional scaling.
    pub pixel_size: (u32, u32),
    /// Grid dimensions.
    pub size: TerminalSize,
    /// Retained visible cells.
    pub cells: Vec<Cell>,
    /// SOL token role for the terminal background.
    pub background: Color,
    /// SOL token role for default terminal text.
    pub foreground: Color,
}

/// Minimal renderer boundary for terminal cells.
pub trait TerminalRenderer {
    fn render_terminal(&mut self, frame: &TerminalFrame);
}

/// Recording renderer fixture that confirms a terminal can be projected without
/// a real display, GPU, or concrete renderer.
#[derive(Debug, Default)]
pub struct RecordingTerminalRenderer {
    /// Submitted frames.
    pub frames: Vec<TerminalFrame>,
}

impl TerminalRenderer for RecordingTerminalRenderer {
    fn render_terminal(&mut self, frame: &TerminalFrame) {
        self.frames.push(frame.clone());
    }
}

/// A terminal tab retained by the application.
pub struct TerminalTab<S: PtySession> {
    session: S,
    grid: TerminalGrid,
    exited: Option<i32>,
}

impl<S: PtySession> TerminalTab<S> {
    fn new(session: S, size: TerminalSize) -> Self {
        Self {
            session,
            grid: TerminalGrid::new(size, 10_000),
            exited: None,
        }
    }
    /// Feed output from a platform PTY-read adapter.
    pub fn feed_output(&mut self, output: &str) {
        self.grid.feed(output);
    }
    /// Return the retained terminal grid.
    #[must_use]
    pub fn grid(&self) -> &TerminalGrid {
        &self.grid
    }
    /// Return child exit code once observed.
    #[must_use]
    pub fn exited(&self) -> Option<i32> {
        self.exited
    }
}

/// First-party Terminal application, parameterized over the two platform
/// boundaries needed for repeatable tests.
pub struct TerminalApp<F: PtyFactory, C: ClipboardAdapter> {
    factory: F,
    clipboard: C,
    shell: ShellProgram,
    pub app: App,
    tabs: Vec<TerminalTab<F::Session>>,
    active_tab: Option<usize>,
    tree: InteractionTree,
    palette: CommandPalette,
}

impl<F: PtyFactory, C: ClipboardAdapter> TerminalApp<F, C> {
    /// Create and start an app with one freshly spawned tab.
    pub fn new(
        factory: F,
        clipboard: C,
        shell: ShellProgram,
        size: TerminalSize,
    ) -> Result<Self, TerminalError> {
        let id = AppId::parse("org.sol.terminal")
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        let mut app = App::new(id);
        app.start()
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        let mut tree = InteractionTree::new("terminal", "Terminal");
        tree.push(SemanticControl::button(
            "new-tab",
            &Button::new().with_label("New tab"),
        ));
        tree.push(SemanticControl::button(
            "copy",
            &Button::new().with_label("Copy selection"),
        ));
        tree.push(SemanticControl::button(
            "paste",
            &Button::new().with_label("Paste"),
        ));
        let mut terminal = Self {
            factory,
            clipboard,
            shell,
            app,
            tabs: Vec::new(),
            active_tab: None,
            tree,
            palette: CommandPalette::new(&TERMINAL_COMMANDS),
        };
        terminal.new_tab(size)?;
        Ok(terminal)
    }

    /// Stable command-palette entries.
    #[must_use]
    pub fn commands(query: &str) -> Vec<PaletteCommand> {
        CommandPalette::filter(&TERMINAL_COMMANDS, query)
    }

    /// Execute a palette command. Search is intentionally UI-owned and returns
    /// no fake system result; use [`Self::search`] for the deterministic data.
    pub fn execute(&mut self, command: &str) -> Result<(), TerminalError> {
        match command {
            "terminal.new_tab" => {
                let size = self.active_grid()?.size();
                self.new_tab(size)
            }
            "terminal.close_tab" => self.close_active_tab(),
            "terminal.copy" => self.copy(Selection {
                anchor: GridPosition { row: 0, column: 0 },
                focus: self.active_grid()?.cursor(),
            }),
            "terminal.paste" => self.paste(),
            "terminal.search" => Ok(()),
            _ => Err(TerminalError::Adapter(format!(
                "unknown terminal command: {command}"
            ))),
        }
    }

    /// Create a new tab through the configured direct-exec PTY factory.
    pub fn new_tab(&mut self, size: TerminalSize) -> Result<(), TerminalError> {
        let session = self.factory.spawn(&self.shell, size)?;
        self.tabs.push(TerminalTab::new(session, size));
        self.active_tab = Some(self.tabs.len() - 1);
        Ok(())
    }

    /// Write literal keyboard text to the active PTY.
    pub fn input_text(&mut self, text: &str) -> Result<(), TerminalError> {
        self.active_tab_mut()?.session.write_input(text.as_bytes())
    }
    /// Send a terminal Enter key.
    pub fn input_enter(&mut self) -> Result<(), TerminalError> {
        self.input_text("\r")
    }
    /// Send a terminal Backspace key.
    pub fn input_backspace(&mut self) -> Result<(), TerminalError> {
        self.active_tab_mut()?.session.write_input(&[0x7f])
    }

    /// Map SOL's normalized editable-key set to terminal input. Focus traversal
    /// is exposed separately by [`Self::handle_navigation`].
    pub fn handle_terminal_key(&mut self, key: Key) -> Result<bool, TerminalError> {
        match key {
            Key::Character(character) => {
                self.input_text(&character.to_string())?;
                Ok(true)
            }
            Key::Enter => {
                self.input_enter()?;
                Ok(true)
            }
            Key::Backspace => {
                self.input_backspace()?;
                Ok(true)
            }
            _ => Ok(false),
        }
    }

    /// Give command controls normal SolUI keyboard focus/navigation behavior.
    pub fn handle_navigation(&mut self, key: Key) -> KeyboardOutcome {
        self.tree.handle_key(key)
    }
    /// Route the shared command-palette key contract and execute activated commands.
    pub fn handle_command_palette_key(
        &mut self,
        key: Key,
    ) -> Result<CommandPaletteOutcome, TerminalError> {
        let outcome = self.palette.handle_key(key);
        if let CommandPaletteOutcome::Execute(id) = outcome {
            self.execute(id)?;
            Ok(CommandPaletteOutcome::Execute(id))
        } else {
            Ok(outcome)
        }
    }
    /// Return the semantic accessibility tree for tab/clipboard commands.
    #[must_use]
    pub fn accessibility_tree(&self) -> AccessibilityNode {
        self.tree.accessibility_tree()
    }
    /// Return the dedicated accessibility projection for the transient palette.
    #[must_use]
    pub fn command_palette_accessibility_tree(&self) -> AccessibilityNode {
        self.palette.accessibility_tree()
    }

    /// Resize both the active grid and the active PTY.
    pub fn resize_active(&mut self, size: TerminalSize) -> Result<(), TerminalError> {
        let tab = self.active_tab_mut()?;
        tab.session.resize(size)?;
        tab.grid.resize(size);
        Ok(())
    }

    /// Feed bytes already read by a platform event loop into the active VT grid.
    pub fn feed_active_output(&mut self, output: &str) -> Result<(), TerminalError> {
        self.active_tab_mut()?.feed_output(output);
        Ok(())
    }
    /// Search the active tab's retained output.
    pub fn search(&self, query: &str) -> Result<Vec<SearchMatch>, TerminalError> {
        Ok(self.active_grid()?.search(query))
    }

    /// Copy an explicit selection through the configured clipboard adapter.
    pub fn copy(&mut self, selection: Selection) -> Result<(), TerminalError> {
        let text = self.active_grid()?.selected_text(selection);
        self.clipboard.set_text(text)
    }
    /// Paste adapter text as literal PTY input; it is never evaluated locally.
    pub fn paste(&mut self) -> Result<(), TerminalError> {
        let text = self.clipboard.get_text()?;
        self.input_text(&text)
    }

    /// Poll all child processes without blocking frame delivery.
    pub fn poll_processes(&mut self) -> Result<(), TerminalError> {
        for tab in &mut self.tabs {
            if tab.exited.is_none() {
                tab.exited = tab.session.poll_exit()?;
            }
        }
        Ok(())
    }

    /// Project the active VT grid into an abstract SOL graphics surface.
    pub fn frame_for(&self, surface: &Surface) -> Result<TerminalFrame, TerminalError> {
        let grid = self.active_grid()?;
        Ok(TerminalFrame {
            pixel_size: (
                (surface.size.0 * surface.scale) as u32,
                (surface.size.1 * surface.scale) as u32,
            ),
            size: grid.size,
            cells: grid.cells.clone(),
            background: Color::Surface,
            foreground: Color::TextPrimary,
        })
    }

    /// Close every child and transition the app lifecycle to stopped.
    pub fn shutdown(&mut self) -> Result<(), TerminalError> {
        for tab in &mut self.tabs {
            if tab.exited.is_none() {
                tab.session.terminate()?;
            }
        }
        self.tabs.clear();
        self.active_tab = None;
        self.app
            .stop()
            .map_err(|error| TerminalError::Adapter(error.to_string()))?;
        Ok(())
    }

    /// Active tab count.
    #[must_use]
    pub fn tab_count(&self) -> usize {
        self.tabs.len()
    }

    fn close_active_tab(&mut self) -> Result<(), TerminalError> {
        let index = self.active_tab.ok_or(TerminalError::NoActiveTab)?;
        let mut tab = self.tabs.remove(index);
        if tab.exited.is_none() {
            tab.session.terminate()?;
        }
        self.active_tab = (!self.tabs.is_empty()).then_some(index.min(self.tabs.len() - 1));
        Ok(())
    }
    fn active_tab_mut(&mut self) -> Result<&mut TerminalTab<F::Session>, TerminalError> {
        let index = self.active_tab.ok_or(TerminalError::NoActiveTab)?;
        self.tabs
            .get_mut(index)
            .ok_or(TerminalError::UnknownTab(index))
    }
    fn active_grid(&self) -> Result<&TerminalGrid, TerminalError> {
        let index = self.active_tab.ok_or(TerminalError::NoActiveTab)?;
        self.tabs
            .get(index)
            .map(|tab| &tab.grid)
            .ok_or(TerminalError::UnknownTab(index))
    }
}

fn main() -> Result<(), Box<dyn Error>> {
    let size = TerminalSize::new(120, 36)?;
    let shell = ShellProgram::from_environment();
    let mut terminal = TerminalApp::new(
        NativePtyFactory,
        MemoryClipboard::default(),
        shell.clone(),
        size,
    )?;
    println!(
        "SOL Terminal — {} tab, PTY started for {}",
        terminal.tab_count(),
        shell.program()
    );
    println!(
        "Command palette: {:?}",
        TerminalApp::<NativePtyFactory, MemoryClipboard>::commands("")
    );
    println!(
        "Native display/GPU and Wayland clipboard adapters are required for an interactive desktop window."
    );
    terminal.shutdown()?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Debug, Default, Clone)]
    struct FakeSession {
        input: Arc<Mutex<Vec<u8>>>,
        sizes: Arc<Mutex<Vec<TerminalSize>>>,
        exit: Option<i32>,
        terminated: bool,
    }
    impl PtySession for FakeSession {
        fn write_input(&mut self, bytes: &[u8]) -> Result<(), TerminalError> {
            self.input
                .lock()
                .map_err(|_| TerminalError::Adapter("fixture input lock poisoned".into()))?
                .extend_from_slice(bytes);
            Ok(())
        }
        fn resize(&mut self, size: TerminalSize) -> Result<(), TerminalError> {
            self.sizes
                .lock()
                .map_err(|_| TerminalError::Adapter("fixture resize lock poisoned".into()))?
                .push(size);
            Ok(())
        }
        fn poll_exit(&mut self) -> Result<Option<i32>, TerminalError> {
            Ok(self.exit)
        }
        fn terminate(&mut self) -> Result<(), TerminalError> {
            self.terminated = true;
            Ok(())
        }
    }
    #[derive(Debug, Default, Clone)]
    struct FakeFactory {
        sessions: Arc<Mutex<Vec<FakeSession>>>,
    }
    impl PtyFactory for FakeFactory {
        type Session = FakeSession;
        fn spawn(
            &self,
            _shell: &ShellProgram,
            _size: TerminalSize,
        ) -> Result<FakeSession, TerminalError> {
            let session = FakeSession::default();
            self.sessions
                .lock()
                .map_err(|_| TerminalError::Adapter("fixture factory lock poisoned".into()))?
                .push(session.clone());
            Ok(session)
        }
    }
    fn app() -> TerminalApp<FakeFactory, MemoryClipboard> {
        TerminalApp::new(
            FakeFactory::default(),
            MemoryClipboard::default(),
            ShellProgram::new("fixture-shell", Vec::new()),
            TerminalSize::new(8, 3).unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn ansi_true_color_unicode_scrollback_and_search_are_deterministic() {
        let mut grid = TerminalGrid::new(TerminalSize::new(40, 2).unwrap(), 4);
        grid.feed("\x1b[38;2;1;2;3m猫");
        let cat = grid.cell(GridPosition { row: 0, column: 0 }).unwrap();
        assert_eq!(cat.text, "猫");
        assert_eq!(
            cat.style.foreground,
            TerminalColor::Rgb(Rgb {
                red: 1,
                green: 2,
                blue: 3,
            })
        );
        grid.feed("\x1b[0m ok\nline two\nneedle");
        assert_eq!(
            grid.search("needle"),
            vec![SearchMatch { row: 2, column: 13 }]
        );
        assert_eq!(
            grid.cell(GridPosition { row: 1, column: 0 })
                .unwrap()
                .style
                .foreground,
            TerminalColor::Default
        );
    }

    #[test]
    fn app_wires_keyboard_resize_selection_clipboard_and_renderer_fixture() {
        let mut terminal = app();
        terminal.feed_active_output("hello\nworld").unwrap();
        terminal
            .copy(Selection {
                anchor: GridPosition { row: 0, column: 0 },
                focus: GridPosition { row: 0, column: 4 },
            })
            .unwrap();
        terminal.paste().unwrap();
        assert!(terminal.handle_terminal_key(Key::Character('!')).unwrap());
        assert!(terminal.handle_terminal_key(Key::Enter).unwrap());
        terminal
            .resize_active(TerminalSize::new(10, 4).unwrap())
            .unwrap();
        assert!(matches!(
            terminal.handle_navigation(Key::Tab),
            KeyboardOutcome::FocusMoved(_)
        ));
        let frame = terminal
            .frame_for(&Surface::high_dpi(320.0, 200.0, 1.25))
            .unwrap();
        let mut renderer = RecordingTerminalRenderer::default();
        renderer.render_terminal(&frame);
        assert_eq!(frame.pixel_size, (400, 250));
        assert_eq!(renderer.frames.len(), 1);
    }

    #[test]
    fn tabs_and_shutdown_have_explicit_process_lifecycle() {
        let mut terminal = app();
        terminal.execute("terminal.new_tab").unwrap();
        assert_eq!(terminal.tab_count(), 2);
        terminal.execute("terminal.close_tab").unwrap();
        assert_eq!(terminal.tab_count(), 1);
        terminal.shutdown().unwrap();
        assert_eq!(terminal.tab_count(), 0);
    }

    #[test]
    fn shared_palette_executes_terminal_commands_and_supports_escape() {
        let mut terminal = app();
        terminal
            .handle_command_palette_key(Key::CommandPalette)
            .unwrap();
        terminal.handle_command_palette_key(Key::Tab).unwrap();
        assert_eq!(
            terminal.handle_command_palette_key(Key::Enter).unwrap(),
            CommandPaletteOutcome::Execute("terminal.new_tab")
        );
        assert_eq!(terminal.tab_count(), 2);
        assert_eq!(
            terminal.handle_command_palette_key(Key::Escape).unwrap(),
            CommandPaletteOutcome::Closed
        );
        assert_eq!(
            terminal
                .handle_command_palette_key(Key::Character('x'))
                .unwrap(),
            CommandPaletteOutcome::Ignored
        );
    }

    #[test]
    fn shell_program_is_direct_exec_not_source_text() {
        let shell = ShellProgram::new("/usr/bin/fish", vec!["--no-config".into()]);
        assert_eq!(shell.program(), "/usr/bin/fish");
        assert_eq!(shell.args(), ["--no-config"]);
        assert!(
            ShellProgram::from_environment().program().starts_with('/')
                || !ShellProgram::from_environment().program().is_empty()
        );
    }
}
