//! Build-script codegen for `sol-boot`.
//!
//! Emits generated modules into `$OUT_DIR`:
//!
//! - `release_key.rs`: the Ed25519 release public key (UEFI targets only).
//! - `sol_mark.rs`: brand-mark geometry parsed from
//!   `assets/branding/sol-mark.svg`, consumed by the boot splash renderer.
//!
//! The SVG parser accepts only the dialect the current asset actually uses
//! (an `<svg viewBox>` containing optional `title`/`desc` plus plain integer
//! `<circle>` elements whose fills are the documented brand variables) and
//! fails the build on anything else. Silent drift between the branded asset
//! and the rendered splash must be impossible.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const BRAND_ASSET: &str = "../../assets/branding/sol-mark.svg";
/// Caps every coordinate so fixed-point scaling products stay inside `u64`.
const MAX_VIEWBOX: u64 = 8_192;

fn main() {
    if let Err(error) = run() {
        panic!("{error}");
    }
}

fn run() -> Result<(), String> {
    println!("cargo:rerun-if-env-changed=SOL_BOOT_PUBLIC_KEY_HEX");
    emit_release_key()?;
    emit_sol_mark()?;
    Ok(())
}

fn out_dir() -> Result<PathBuf, String> {
    env::var_os("OUT_DIR")
        .map(PathBuf::from)
        .ok_or_else(|| "Cargo did not provide OUT_DIR".to_owned())
}

fn write_generated(path: &Path, source: &str) -> Result<(), String> {
    fs::write(path, source).map_err(|error| format!("cannot write {}: {error}", path.display()))
}

fn emit_release_key() -> Result<(), String> {
    if env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("uefi") {
        return Ok(());
    }
    let encoded = env::var("SOL_BOOT_PUBLIC_KEY_HEX").map_err(|_| {
        "SOL_BOOT_PUBLIC_KEY_HEX must contain the 64-hex-digit Ed25519 release public key"
            .to_owned()
    })?;
    if encoded.len() != 64 || !encoded.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(
            "SOL_BOOT_PUBLIC_KEY_HEX must contain exactly 64 hexadecimal digits".to_owned(),
        );
    }
    let mut values = Vec::with_capacity(32);
    for offset in (0..64).step_by(2) {
        values.push(
            u8::from_str_radix(&encoded[offset..offset + 2], 16)
                .map_err(|error| format!("invalid public key: {error}"))?,
        );
    }
    let source = format!("pub const RELEASE_KEY: [u8; 32] = {values:?};\n");
    write_generated(&out_dir()?.join("release_key.rs"), &source)
}

fn emit_sol_mark() -> Result<(), String> {
    let manifest = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "Cargo did not provide CARGO_MANIFEST_DIR".to_owned())?,
    );
    let asset_path = manifest.join(BRAND_ASSET);
    println!("cargo:rerun-if-changed={}", asset_path.display());
    let svg = fs::read_to_string(&asset_path)
        .map_err(|error| format!("cannot read {}: {error}", asset_path.display()))?;
    let mark = parse_mark(&svg).map_err(|error| format!("{}: {error}", asset_path.display()))?;
    write_generated(&out_dir()?.join("sol_mark.rs"), &render_codegen(&mark))
}

#[derive(Debug)]
enum BrandFill {
    Foreground,
    Cutout,
}

#[derive(Debug)]
struct BrandCircle {
    cx: u64,
    cy: u64,
    r: u64,
    fill: BrandFill,
}

#[derive(Debug)]
struct BrandMark {
    viewbox: u64,
    circles: Vec<BrandCircle>,
}

fn render_codegen(mark: &BrandMark) -> String {
    #[allow(
        clippy::unnecessary_join,
        reason = "each row is built independently; the count is only known at build time"
    )]
    let circles = mark
        .circles
        .iter()
        .map(|circle| {
            let kind = match circle.fill {
                BrandFill::Foreground => "Foreground",
                BrandFill::Cutout => "Cutout",
            };
            format!(
                "    BrandCircle {{ cx: {}, cy: {}, r: {}, fill: BrandFill::{kind} }},\n",
                circle.cx, circle.cy, circle.r
            )
        })
        .collect::<Vec<_>>()
        .join("");
    // The enclosing module is private, so plain `pub` here exposes nothing
    // beyond `splash::brand` while satisfying visibility lints.
    format!(
        "// @generated by boot/sol-boot/build.rs from assets/branding/sol-mark.svg.\n\
         // Coordinates are unsigned integers in viewBox units; do not edit.\n\
         #[derive(Debug, Clone, Copy)]\npub enum BrandFill {{\n    Foreground,\n    Cutout,\n}}\n\n\
         #[derive(Debug, Clone, Copy)]\npub struct BrandCircle {{\n    pub cx: u64,\n    pub cy: u64,\n    pub r: u64,\n    pub fill: BrandFill,\n}}\n\n\
         pub const BRAND_VIEWBOX: u64 = {};\n\n\
         pub const BRAND_CIRCLES: [BrandCircle; {}] = [\n{}];\n",
        mark.viewbox,
        mark.circles.len(),
        circles
    )
}

/// Parses the exact grammar
///
/// ```text
/// [xml-decl|comment|doctype]* <svg attrs> [trivia|title|desc|circle]* </svg> [trivia]
/// ```
///
/// `title`/`desc` bodies are skipped verbatim (plain text, no nesting). Any
/// other construct is rejected so an unexpected redesign fails the build
/// instead of silently rendering stale art.
fn parse_mark(svg: &str) -> Result<BrandMark, String> {
    let mut rest = svg;
    rest = skip_trivia(rest);
    let opening_inner = open_tag(&mut rest, "svg")?;
    let viewbox = viewbox_from_attrs(opening_inner)?;
    let mut circles = Vec::new();
    loop {
        rest = skip_trivia(rest);
        if let Some(after) = rest.strip_prefix("</") {
            rest = after;
            expect_word(&mut rest, "svg")?;
            expect_close(&mut rest)?;
            break;
        }
        if let Some(name) = ["title", "desc"]
            .into_iter()
            .find(|name| tag_opens(rest, name))
        {
            consume_tag_open(&mut rest, name);
            skip_text_body(&mut rest)?;
            expect_closing(&mut rest, name)?;
            continue;
        }
        if tag_opens(rest, "circle") {
            consume_tag_open(&mut rest, "circle");
            let inner = read_to_tag_end(&mut rest)?;
            circles.push(circle_from_attrs(inner)?);
            continue;
        }
        return Err(format!(
            "expected '</svg>', title, desc, or circle near '{}'",
            truncate(rest)
        ));
    }
    rest = skip_trivia(rest);
    if !rest.is_empty() {
        return Err(format!(
            "unexpected trailing content near '{}'",
            truncate(rest)
        ));
    }
    Ok(BrandMark { viewbox, circles })
}

/// Reads the attribute list up to `>` of an already-named start tag.
fn open_tag<'a>(rest: &mut &'a str, name: &str) -> Result<&'a str, String> {
    let Some(after_lt) = rest.strip_prefix('<') else {
        return Err(format!("expected '<{name}' near '{}'", truncate(rest)));
    };
    *rest = after_lt;
    expect_word(rest, name)?;
    read_to_tag_end(rest)
}

fn tag_opens(rest: &str, name: &str) -> bool {
    let Some(after_lt) = rest.strip_prefix('<') else {
        return false;
    };
    let Some(after_name) = after_lt.strip_prefix(name) else {
        return false;
    };
    // A real tag boundary follows the name (whitespace, slash, or '>').
    after_name.starts_with([' ', '\t', '\r', '\n', '/', '>'])
}

fn consume_tag_open(rest: &mut &str, name: &str) {
    *rest = &rest[1 + name.len()..];
}

/// Consumes through the closing `>` of a start tag and returns its attribute
/// text. Rejects nested `<` to keep the grammar flat.
fn read_to_tag_end<'a>(rest: &mut &'a str) -> Result<&'a str, String> {
    let end = rest
        .find('>')
        .ok_or_else(|| format!("unterminated start tag near '{}'", truncate(rest)))?;
    if rest[..end].contains('<') {
        return Err(format!(
            "nested markup inside a start tag near '{}'",
            truncate(rest)
        ));
    }
    let (inner, after) = rest.split_at(end);
    *rest = &after[1..];
    Ok(inner)
}

fn skip_text_body(rest: &mut &str) -> Result<(), String> {
    let close = rest
        .find("</")
        .ok_or_else(|| format!("title/desc body is not closed before '{}'", truncate(rest)))?;
    if rest[..close].contains('<') {
        return Err("nested markup inside title/desc is unsupported".to_owned());
    }
    *rest = &rest[close + 2..];
    Ok(())
}

fn expect_closing(rest: &mut &str, name: &str) -> Result<(), String> {
    expect_word(rest, name)?;
    expect_close(rest)
}

fn expect_word(rest: &mut &str, word: &str) -> Result<(), String> {
    let trimmed = rest.trim_start();
    let Some(after) = trimmed.strip_prefix(word) else {
        return Err(format!("expected '{word}' near '{}'", truncate(trimmed)));
    };
    *rest = after;
    Ok(())
}

fn expect_close(rest: &mut &str) -> Result<(), String> {
    let trimmed = rest.trim_start();
    let Some(after) = trimmed.strip_prefix('>') else {
        return Err(format!("expected '>' near '{}'", truncate(trimmed)));
    };
    *rest = after;
    Ok(())
}

/// Skips whitespace, comments, the XML declaration, and DOCTYPE entries.
fn skip_trivia(mut rest: &str) -> &str {
    loop {
        rest = rest.trim_start();
        if let Some(after) = rest.strip_prefix("<!--") {
            if let Some(end) = after.find("-->") {
                rest = &after[end + 3..];
                continue;
            }
            return "";
        }
        if let Some(after) = rest.strip_prefix("<?xml") {
            if let Some(end) = after.find("?>") {
                rest = &after[end + 2..];
                continue;
            }
            return "";
        }
        if rest.starts_with("<!DOCTYPE") {
            match rest.find('>') {
                Some(end) => {
                    rest = &rest[end + 1..];
                    continue;
                }
                None => return "",
            }
        }
        return rest;
    }
}

fn circle_from_attrs(inner: &str) -> Result<BrandCircle, String> {
    let mut cx: Option<u64> = None;
    let mut cy: Option<u64> = None;
    let mut radius: Option<u64> = None;
    let mut fill: Option<BrandFill> = None;
    for (name, value) in attributes(inner)? {
        match name {
            "cx" => cx = Some(parse_viewbox_units(value)?),
            "cy" => cy = Some(parse_viewbox_units(value)?),
            "r" => radius = Some(parse_positive(value)?),
            "fill" => fill = Some(classify_fill(value)?),
            other => return Err(format!("unsupported <circle> attribute '{other}'")),
        }
    }
    Ok(BrandCircle {
        cx: cx.ok_or_else(|| "<circle> lacks cx".to_owned())?,
        cy: cy.ok_or_else(|| "<circle> lacks cy".to_owned())?,
        r: radius.ok_or_else(|| "<circle> lacks r".to_owned())?,
        fill: fill.ok_or_else(|| "<circle> lacks a supported fill".to_owned())?,
    })
}

fn viewbox_from_attrs(inner: &str) -> Result<u64, String> {
    let mut components: Option<[u64; 4]> = None;
    for (name, value) in attributes(inner)? {
        match name {
            "viewBox" => {
                let parts: [&str; 4] = value
                    .split_whitespace()
                    .collect::<Vec<_>>()
                    .try_into()
                    .map_err(|_| "viewBox needs exactly four components".to_owned())?;
                let parsed = parts
                    .iter()
                    .copied()
                    .map(parse_viewbox_units)
                    .collect::<Result<Vec<_>, _>>()?;
                components = Some(
                    parsed
                        .try_into()
                        .map_err(|_| "viewBox needs exactly four components".to_owned())?,
                );
            }
            "xmlns"
            | "xmlns:xlink"
            | "width"
            | "height"
            | "preserveAspectRatio"
            | "role"
            | "aria-label"
            | "aria-labelledby"
            | "class"
            | "id" => {}
            other => return Err(format!("unsupported <svg> attribute '{other}'")),
        }
    }
    let [min_x, min_y, width, height] =
        components.ok_or_else(|| "svg element lacks a viewBox".to_owned())?;
    if min_x != 0 || min_y != 0 {
        return Err("viewBox must be anchored at 0 0".to_owned());
    }
    if width != height || width == 0 {
        return Err("viewBox must be square and non-empty".to_owned());
    }
    Ok(width)
}

/// Quote-aware attribute tokenizer: `name="value"` pairs separated by
/// whitespace, values possibly containing spaces (`viewBox="0 0 512 512"`).
fn attributes(inner: &str) -> Result<Vec<(&str, &str)>, String> {
    let mut rest = inner.trim();
    if let Some(without_slash) = rest.strip_suffix('/') {
        rest = without_slash.trim_end();
    }
    let mut pairs = Vec::new();
    while !rest.is_empty() {
        let eq = rest
            .find('=')
            .ok_or_else(|| format!("attribute lacks '=' near '{}'", truncate(rest)))?;
        let name = rest[..eq].trim_end();
        if name.is_empty() || !name.bytes().all(is_attribute_name_byte) {
            return Err(format!("malformed attribute name '{name}'"));
        }
        rest = rest[eq + 1..].trim_start();
        let quote = rest
            .chars()
            .next()
            .ok_or_else(|| format!("attribute '{name}' lacks a value"))?;
        if quote != '"' && quote != '\'' {
            return Err(format!("attribute '{name}' value must be quoted"));
        }
        let value_start = quote.len_utf8();
        let value_rest = &rest[value_start..];
        let value_end = value_rest
            .find(quote)
            .ok_or_else(|| format!("attribute '{name}' value is not terminated"))?;
        pairs.push((name, &value_rest[..value_end]));
        rest = value_rest[value_end + quote.len_utf8()..].trim_start();
    }
    Ok(pairs)
}

const fn is_attribute_name_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b':' | b'.')
}

/// Accepts both the documented CSS variables and their concrete fallback
/// spellings so flattening the asset later stays a no-op for the bootloader.
fn classify_fill(raw: &str) -> Result<BrandFill, String> {
    const EXPECTED: &str =
        "expected var(--sol-mark-foreground|--sol-mark-background[, fallback]) or #rgb";
    let head = raw.trim();
    let head = head.strip_prefix("var(").unwrap_or(head);
    let head = head.strip_suffix(')').unwrap_or(head);
    let head = head.split(',').next().unwrap_or("").trim();
    match head.to_ascii_lowercase().as_str() {
        "--sol-mark-foreground" | "#fff" | "#ffffff" | "white" => Ok(BrandFill::Foreground),
        "--sol-mark-background" | "#000" | "#000000" | "black" => Ok(BrandFill::Cutout),
        _ => Err(format!("unsupported fill '{raw}'; {EXPECTED}")),
    }
}

/// Plain non-negative integer literals only; fractional, negative, and
/// oversized coordinates are rejected so generated code stays literal-safe.
fn parse_viewbox_units(raw: &str) -> Result<u64, String> {
    parse_integer(raw).and_then(|value| {
        if value > MAX_VIEWBOX {
            Err(format!(
                "coordinate '{raw}' exceeds supported bound {MAX_VIEWBOX}"
            ))
        } else {
            Ok(value)
        }
    })
}

fn parse_positive(raw: &str) -> Result<u64, String> {
    parse_integer(raw).and_then(|value| {
        if value == 0 {
            Err("radius must be positive".to_owned())
        } else {
            Ok(value)
        }
    })
}

fn parse_integer(raw: &str) -> Result<u64, String> {
    if raw.is_empty() || !raw.bytes().all(|byte| byte.is_ascii_digit()) {
        return Err(format!("'{raw}' is not a non-negative integer"));
    }
    raw.parse::<u64>()
        .map_err(|_| format!("'{raw}' exceeds supported magnitude"))
}

fn truncate(raw: &str) -> &str {
    match raw.char_indices().nth(24) {
        Some((index, _)) => &raw[..index],
        None => raw,
    }
}
