[package]
name = "sol-boot"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "sol-boot"
path = "src/main.rs"

[[bin]]
name = "sol-boot-test-payload"
path = "src/test_payload.rs"
required-features = ["ovmf-test-payload"]

[features]
ovmf-test-payload = []

[dependencies]
ed25519-dalek = { version = "2.2", default-features = false, features = ["fast"] }
sha2 = { version = "0.10", default-features = false }
sol-boot-core = { path = "../sol-boot-core" }

[target.'cfg(target_os = "uefi")'.dependencies]
uefi = { version = "0.39", features = ["alloc", "global_allocator"] }

[lints]
workspace = true
