[package]
name = "sol-graphics"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish = false

[dependencies]
sol-design = { path = "../sol-design" }

[features]
default = []
#slint = ["dep:slint"]

[dev-dependencies]
