[package]
name = "sol-files"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[dependencies]
image = { version = "0.25", default-features = false, features = ["gif", "jpeg", "png", "webp"] }
sol-app = { path = "../../sdk/sol-app" }
sol-design = { path = "../../sdk/sol-design" }
sol-ui = { path = "../../sdk/sol-ui" }
